### ISSUE TITLE
banned/hidden/restricted(?) users are shown on api

### ISSUE THREAD

**Issue by Piotrekol** [ppy/osu-api#111]
mapID: 51077
mode: 0
username: hameron120
userID: 3375977
rank as of time of writing: 99
https://osu.ppy.sh/api/get_scores?k=<key>&b=51077&m=0&limit=100
```
[{"score_id":"969043954","score":"4361149","username":"azuraer","maxcombo":"440","count50":"0","count100":"14","count300":"307","countmiss":"0","countkatu":"12","countgeki":"61","perfect":"1","enabled_mods":"1048","user_id":"145851","date":"2012-12-12 22:52:38","rank":"SH","pp":"102.776"},{"score_id":"1299211266","score":"4251111","username":"ShadowSoul","maxcombo":"440","count50":"0","count100":"1","count300":"320","countmiss":"0","countkatu":"1","countgeki":"72","perfect":"1","enabled_mods":"72","user_id":"494970","date":"2013-07-16 21:55:36","rank":"SH","pp":"210.989"},{"score_id":"950737217","score":"4248378","username":"Darksonic","maxcombo":"440","count50":"0","count100":"1","count300":"320","countmiss":"0","countkatu":"1","countgeki":"72","perfect":"1","enabled_mods":"72","user_id":"570042","date":"2012-11-29 14:08:54","rank":"SH","pp":"210.989"},{"score_id":"1953802475","score":"4245832","username":"Dsan","maxcombo":"440","count50":"0","count100":"1","count300":"320","countmiss":"0","countkatu":"1","countgeki":"72","perfect":"1","enabled_mods":"584","user_id":"1266166","date":"2015-07-07 22:34:37","rank":"SH","pp":"210.989"},{"score_id":"828776824","score":"4238904","username":"-shunino-","maxcombo":"440","count50":"1","count100":"1","count300":"319","countmiss":"0","countkatu":"1","countgeki":"71","perfect":"1","enabled_mods":"72","user_id":"1063633","date":"2012-08-17 11:29:20","rank":"SH","pp":"201.677"},{"score_id":"1462451173","score":"4235369","username":"Rucker","maxcombo":"440","count50":"0","count100":"3","count300":"318","countmiss":"0","countkatu":"3","countgeki":"70","perfect":"1","enabled_mods":"72","user_id":"147515","date":"2013-10-12 22:04:06","rank":"SH","pp":"196.459"},{"score_id":"927188281","score":"4231038","username":"N a n o","maxcombo":"440","count50":"0","count100":"3","count300":"318","countmiss":"0","countkatu":"3","countgeki":"70","perfect":"1","enabled_mods":"72","user_id":"694114","date":"2012-11-10 15:28:10","rank":"SH","pp":"196.459"},{"score_id":"1228600264","score":"4228868","username":"[ Beatrice ]","maxcombo":"440","count50":"0","count100":"3","count300":"318","countmiss":"0","countkatu":"2","countgeki":"71","perfect":"1","enabled_mods":"72","user_id":"683791","date":"2013-06-08 02:06:59","rank":"SH","pp":"196.459"},{"score_id":"1739443871","score":"4228640","username":"Pain","maxcombo":"440","count50":"0","count100":"3","count300":"318","countmiss":"0","countkatu":"3","countgeki":"70","perfect":"1","enabled_mods":"72","user_id":"1460263","date":"2014-05-10 13:08:14","rank":"SH","pp":"196.459"},{"score_id":"632940823","score":"4225679","username":"WubWoofWolf","maxcombo":"440","count50":"0","count100":"3","count300":"318","countmiss":"0","countkatu":"3","countgeki":"70","perfect":"1","enabled_mods":"72","user_id":"39828","date":"2012-03-20 01:44:41","rank":"SH","pp":"196.459"},{"score_id":"1041945965","score":"4222029","username":"TaNaBaTa","maxcombo":"440","count50":"0","count100":"7","count300":"314","countmiss":"0","countkatu":"7","countgeki":"66","perfect":"1","enabled_mods":"72","user_id":"756273","date":"2013-02-03 01:17:47","rank":"SH","pp":"172.745"},{"score_id":"1339696880","score":"4217745","username":"Nitro","maxcombo":"440","count50":"1","count100":"3","count300":"317","countmiss":"0","countkatu":"2","countgeki":"70","perfect":"1","enabled_mods":"72","user_id":"654098","date":"2013-08-07 16:40:26","rank":"SH","pp":"188.335"},{"score_id":"950620294","score":"4213242","username":"BinJip","maxcombo":"439","count50":"1","count100":"3","count300":"317","countmiss":"0","countkatu":"2","countgeki":"70","perfect":"0","enabled_mods":"76","user_id":"261694","date":"2012-11-29 10:55:34","rank":"SH","pp":"188.154"},{"score_id":"728342272","score":"4208223","username":"Forseen","maxcombo":"440","count50":"0","count100":"5","count300":"316","countmiss":"0","countkatu":"5","countgeki":"68","perfect":"1","enabled_mods":"72","user_id":"556012","date":"2012-06-06 01:15:58","rank":"SH","pp":"183.786"},{"score_id":"1044771033","score":"4207972","username":"Mayzel","maxcombo":"440","count50":"0","count100":"7","count300":"314","countmiss":"0","countkatu":"6","countgeki":"67","perfect":"1","enabled_mods":"72","user_id":"696435","date":"2013-02-04 23:33:53","rank":"SH","pp":"172.745"},{"score_id":"1911718642","score":"4207847","username":"DrakRainbow","maxcombo":"440","count50":"0","count100":"8","count300":"313","countmiss":"0","countkatu":"7","countgeki":"66","perfect":"1","enabled_mods":"72","user_id":"1320231","date":"2015-04-05 00:23:13","rank":"SH","pp":"167.772"},{"score_id":"1910827023","score":"4206805","username":"Nicokarl","maxcombo":"440","count50":"0","count100":"4","count300":"317","countmiss":"0","countkatu":"3","countgeki":"70","perfect":"1","enabled_mods":"72","user_id":"1600281","date":"2015-04-03 08:46:34","rank":"SH","pp":"189.905"},{"score_id":"1579453459","score":"4203745","username":"-Nakano Azusa-","maxcombo":"440","count50":"0","count100":"8","count300":"313","countmiss":"0","countkatu":"7","countgeki":"66","perfect":"1","enabled_mods":"72","user_id":"1743553","date":"2013-12-08 18:02:47","rank":"SH","pp":"167.772"},{"score_id":"1306341526","score":"4200801","username":"Akiko-","maxcombo":"440","count50":"0","count100":"6","count300":"315","countmiss":"0","countkatu":"6","countgeki":"67","perfect":"1","enabled_mods":"72","user_id":"1226106","date":"2013-07-20 19:07:06","rank":"SH","pp":"178.075"},{"score_id":"1838400312","score":"4199712","username":"Forget me not","maxcombo":"440","count50":"0","count100":"12","count300":"309","countmiss":"0","countkatu":"10","countgeki":"63","perfect":"1","enabled_mods":"72","user_id":"1850191","date":"2014-12-28 19:57:39","rank":"SH","pp":"151.013"},{"score_id":"1142456262","score":"4199692","username":"Shimox","maxcombo":"439","count50":"0","count100":"6","count300":"315","countmiss":"0","countkatu":"5","countgeki":"68","perfect":"0","enabled_mods":"72","user_id":"1192387","date":"2013-04-14 07:43:06","rank":"SH","pp":"177.892"},{"score_id":"1943231024","score":"4196647","username":"Nagata-","maxcombo":"440","count50":"0","count100":"9","count300":"312","countmiss":"0","countkatu":"6","countgeki":"67","perfect":"1","enabled_mods":"72","user_id":"4437068","date":"2015-06-14 13:27:34","rank":"SH","pp":"163.133"},{"score_id":"1916294567","score":"4195595","username":"AIiceXD","maxcombo":"440","count50":"0","count100":"6","count300":"315","countmiss":"0","countkatu":"5","countgeki":"68","perfect":"1","enabled_mods":"72","user_id":"3321136","date":"2015-04-14 14:59:23","rank":"SH","pp":"178.075"},{"score_id":"1663708691","score":"4193779","username":"cr1m","maxcombo":"440","count50":"0","count100":"7","count300":"314","countmiss":"0","countkatu":"5","countgeki":"68","perfect":"1","enabled_mods":"72","user_id":"803766","date":"2014-01-14 05:40:48","rank":"SH","pp":"172.745"},{"score_id":"1363140288","score":"4191730","username":"Dark and Hard","maxcombo":"440","count50":"1","count100":"6","count300":"314","countmiss":"0","countkatu":"4","countgeki":"68","perfect":"1","enabled_mods":"72","user_id":"1208727","date":"2013-08-19 15:13:43","rank":"SH","pp":"171.469"},{"score_id":"1579475608","score":"4190305","username":"KAKALOTE","maxcombo":"440","count50":"0","count100":"7","count300":"314","countmiss":"0","countkatu":"4","countgeki":"69","perfect":"1","enabled_mods":"72","user_id":"1840225","date":"2013-12-08 18:15:34","rank":"SH","pp":"172.745"},{"score_id":"1092177871","score":"4189775","username":"Silynn","maxcombo":"440","count50":"1","count100":"5","count300":"315","countmiss":"0","countkatu":"4","countgeki":"68","perfect":"1","enabled_mods":"72","user_id":"1171628","date":"2013-03-10 07:22:48","rank":"SH","pp":"176.707"},{"score_id":"1237101939","score":"4188873","username":"5231Jing","maxcombo":"440","count50":"0","count100":"10","count300":"311","countmiss":"0","countkatu":"9","countgeki":"64","perfect":"1","enabled_mods":"72","user_id":"181057","date":"2013-06-12 19:24:34","rank":"SH","pp":"158.807"},{"score_id":"1348327886","score":"4184904","username":"Grinder","maxcombo":"440","count50":"0","count100":"8","count300":"313","countmiss":"0","countkatu":"7","countgeki":"66","perfect":"1","enabled_mods":"584","user_id":"1570150","date":"2013-08-11 23:55:28","rank":"SH","pp":"167.772"},{"score_id":"1816254935","score":"4183108","username":"Osama","maxcombo":"440","count50":"1","count100":"5","count300":"315","countmiss":"0","countkatu":"4","countgeki":"68","perfect":"1","enabled_mods":"72","user_id":"799218","date":"2014-11-09 19:46:08","rank":"SH","pp":"176.707"},{"score_id":"1765752546","score":"4182366","username":"yukiotokoNy","maxcombo":"440","count50":"0","count100":"7","count300":"314","countmiss":"0","countkatu":"4","countgeki":"69","perfect":"1","enabled_mods":"72","user_id":"935491","date":"2014-07-09 23:11:15","rank":"SH","pp":"172.745"},{"score_id":"1416047504","score":"4177626","username":"DarK-AnGeL","maxcombo":"440","count50":"0","count100":"10","count300":"311","countmiss":"0","countkatu":"9","countgeki":"64","perfect":"1","enabled_mods":"72","user_id":"2044501","date":"2013-09-16 21:40:22","rank":"SH","pp":"158.807"},{"score_id":"1768752588","score":"4176438","username":"Saya-Eternal","maxcombo":"440","count50":"0","count100":"11","count300":"310","countmiss":"0","countkatu":"8","countgeki":"65","perfect":"1","enabled_mods":"72","user_id":"2865291","date":"2014-07-16 21:28:07","rank":"SH","pp":"154.773"},{"score_id":"1184924357","score":"4176124","username":"Miu Matsuoka","maxcombo":"440","count50":"0","count100":"8","count300":"313","countmiss":"0","countkatu":"5","countgeki":"68","perfect":"1","enabled_mods":"72","user_id":"10641","date":"2013-05-12 02:18:52","rank":"SH","pp":"167.772"},{"score_id":"796807573","score":"4173572","username":"Torein 13rd","maxcombo":"440","count50":"0","count100":"9","count300":"312","countmiss":"0","countkatu":"6","countgeki":"67","perfect":"1","enabled_mods":"72","user_id":"263687","date":"2012-07-26 03:47:46","rank":"SH","pp":"163.133"},{"score_id":"778505983","score":"4171223","username":"Yuleiyu","maxcombo":"440","count50":"0","count100":"8","count300":"313","countmiss":"0","countkatu":"7","countgeki":"66","perfect":"1","enabled_mods":"72","user_id":"751695","date":"2012-07-13 02:02:15","rank":"SH","pp":"167.772"},{"score_id":"1491190181","score":"4170491","username":"i2m_zhou","maxcombo":"440","count50":"0","count100":"13","count300":"308","countmiss":"0","countkatu":"11","countgeki":"62","perfect":"1","enabled_mods":"72","user_id":"799939","date":"2013-10-27 19:42:56","rank":"SH","pp":"147.508"},{"score_id":"1189053831","score":"4169362","username":"Yap","maxcombo":"440","count50":"0","count100":"12","count300":"309","countmiss":"0","countkatu":"11","countgeki":"62","perfect":"1","enabled_mods":"72","user_id":"803348","date":"2013-05-14 21:19:03","rank":"SH","pp":"151.013"},{"score_id":"1942975613","score":"4162599","username":"Mercurius","maxcombo":"440","count50":"0","count100":"10","count300":"311","countmiss":"0","countkatu":"8","countgeki":"65","perfect":"1","enabled_mods":"72","user_id":"589550","date":"2015-06-14 00:31:08","rank":"SH","pp":"158.807"},{"score_id":"1342194414","score":"4161811","username":"InabaTewi","maxcombo":"440","count50":"0","count100":"11","count300":"310","countmiss":"0","countkatu":"8","countgeki":"65","perfect":"1","enabled_mods":"72","user_id":"1078004","date":"2013-08-08 22:33:24","rank":"SH","pp":"154.773"},{"score_id":"1822360381","score":"4161806","username":"Suzutsuki-","maxcombo":"439","count50":"0","count100":"16","count300":"305","countmiss":"0","countkatu":"11","countgeki":"62","perfect":"0","enabled_mods":"72","user_id":"1026028","date":"2014-11-23 22:13:09","rank":"SH","pp":"138.177"},{"score_id":"1034403099","score":"4161191","username":"Synnex","maxcombo":"440","count50":"0","count100":"14","count300":"307","countmiss":"0","countkatu":"10","countgeki":"63","perfect":"1","enabled_mods":"72","user_id":"1397777","date":"2013-01-28 23:43:29","rank":"SH","pp":"144.241"},{"score_id":"1933909785","score":"4160727","username":"[Toy]","maxcombo":"440","count50":"1","count100":"9","count300":"311","countmiss":"0","countkatu":"8","countgeki":"64","perfect":"1","enabled_mods":"72","user_id":"2757689","date":"2015-05-24 09:23:15","rank":"SH","pp":"157.772"},{"score_id":"1404571399","score":"4160517","username":"TTTL","maxcombo":"440","count50":"2","count100":"14","count300":"305","countmiss":"0","countkatu":"7","countgeki":"65","perfect":"1","enabled_mods":"72","user_id":"164583","date":"2013-09-10 12:43:00","rank":"SH","pp":"137.017"},{"score_id":"605045472","score":"4159177","username":"M A I D","maxcombo":"440","count50":"0","count100":"12","count300":"309","countmiss":"0","countkatu":"9","countgeki":"64","perfect":"1","enabled_mods":"76","user_id":"216472","date":"2012-02-25 11:28:47","rank":"SH","pp":"151.013"},{"score_id":"738424658","score":"4158709","username":"rockleejkooo","maxcombo":"440","count50":"0","count100":"10","count300":"311","countmiss":"0","countkatu":"9","countgeki":"64","perfect":"1","enabled_mods":"76","user_id":"384003","date":"2012-06-13 17:55:49","rank":"SH","pp":"158.807"},{"score_id":"1135081148","score":"4155504","username":"MUXIA","maxcombo":"440","count50":"0","count100":"14","count300":"307","countmiss":"0","countkatu":"11","countgeki":"62","perfect":"1","enabled_mods":"72","user_id":"1077975","date":"2013-04-08 23:50:39","rank":"SH","pp":"144.241"},{"score_id":"1324716057","score":"4154824","username":"Kanon","maxcombo":"440","count50":"0","count100":"11","count300":"310","countmiss":"0","countkatu":"10","countgeki":"63","perfect":"1","enabled_mods":"72","user_id":"109249","date":"2013-07-30 15:16:32","rank":"SH","pp":"154.773"},{"score_id":"1966078330","score":"4149440","username":"Ookura Risona","maxcombo":"440","count50":"0","count100":"10","count300":"311","countmiss":"0","countkatu":"5","countgeki":"68","perfect":"1","enabled_mods":"584","user_id":"2073644","date":"2015-08-02 10:59:34","rank":"SH","pp":"158.807"},{"score_id":"777982780","score":"4143810","username":"LQX","maxcombo":"440","count50":"1","count100":"14","count300":"306","countmiss":"0","countkatu":"13","countgeki":"59","perfect":"1","enabled_mods":"584","user_id":"203889","date":"2012-07-12 19:11:19","rank":"SH","pp":"140.47"},{"score_id":"1086406989","score":"4143150","username":"Swatty","maxcombo":"440","count50":"0","count100":"12","count300":"309","countmiss":"0","countkatu":"9","countgeki":"64","perfect":"1","enabled_mods":"72","user_id":"1028683","date":"2013-03-06 01:34:45","rank":"SH","pp":"151.013"},{"score_id":"1750198665","score":"4141164","username":"- G I D Z -","maxcombo":"440","count50":"0","count100":"13","count300":"308","countmiss":"0","countkatu":"10","countgeki":"63","perfect":"1","enabled_mods":"72","user_id":"2286528","date":"2014-06-04 18:36:18","rank":"SH","pp":"147.508"},{"score_id":"1334776097","score":"4140672","username":"MeguL1Ne","maxcombo":"440","count50":"0","count100":"14","count300":"307","countmiss":"0","countkatu":"12","countgeki":"61","perfect":"1","enabled_mods":"72","user_id":"1490076","date":"2013-08-05 00:19:29","rank":"SH","pp":"144.241"},{"score_id":"1919505166","score":"4138651","username":"G e o n","maxcombo":"439","count50":"0","count100":"13","count300":"308","countmiss":"0","countkatu":"7","countgeki":"66","perfect":"0","enabled_mods":"584","user_id":"664217","date":"2015-04-21 22:39:35","rank":"SH","pp":"147.324"},{"score_id":"1174366332","score":"4134190","username":"SwENeMbO","maxcombo":"440","count50":"1","count100":"13","count300":"307","countmiss":"0","countkatu":"9","countgeki":"63","perfect":"1","enabled_mods":"72","user_id":"652793","date":"2013-05-05 11:32:55","rank":"SH","pp":"143.46"},{"score_id":"1935018845","score":"4131100","username":"[ baka 3b ]","maxcombo":"440","count50":"1","count100":"12","count300":"308","countmiss":"0","countkatu":"10","countgeki":"62","perfect":"1","enabled_mods":"72","user_id":"3016611","date":"2015-05-26 22:32:20","rank":"SH","pp":"146.669"},{"score_id":"1226636618","score":"4130638","username":"akihi","maxcombo":"440","count50":"0","count100":"17","count300":"304","countmiss":"0","countkatu":"15","countgeki":"58","perfect":"1","enabled_mods":"72","user_id":"181847","date":"2013-06-06 23:47:13","rank":"SH","pp":"135.72"},{"score_id":"1974569481","score":"4130386","username":"Ishkiz","maxcombo":"440","count50":"0","count100":"12","count300":"309","countmiss":"0","countkatu":"10","countgeki":"63","perfect":"1","enabled_mods":"72","user_id":"2528325","date":"2015-08-20 04:46:45","rank":"SH","pp":"151.013"},{"score_id":"1945088052","score":"4127833","username":"Leaf","maxcombo":"440","count50":"0","count100":"16","count300":"305","countmiss":"0","countkatu":"11","countgeki":"62","perfect":"1","enabled_mods":"72","user_id":"1380419","date":"2015-06-18 23:23:59","rank":"SH","pp":"138.362"},{"score_id":"202610419","score":"4126204","username":"KRZY","maxcombo":"439","count50":"1","count100":"14","count300":"306","countmiss":"0","countkatu":"8","countgeki":"64","perfect":"0","enabled_mods":"76","user_id":"114017","date":"2010-12-23 18:10:23","rank":"SH","pp":"140.285"},{"score_id":"888059929","score":"4124905","username":"Lunarhiro","maxcombo":"440","count50":"2","count100":"13","count300":"306","countmiss":"0","countkatu":"12","countgeki":"60","perfect":"1","enabled_mods":"72","user_id":"288492","date":"2012-10-07 03:45:40","rank":"SH","pp":"139.755"},{"score_id":"1725043810","score":"4122241","username":"z980838928","maxcombo":"440","count50":"0","count100":"17","count300":"304","countmiss":"0","countkatu":"11","countgeki":"62","perfect":"1","enabled_mods":"72","user_id":"1355695","date":"2014-04-05 21:37:56","rank":"SH","pp":"135.72"},{"score_id":"165955344","score":"4119072","username":"LemonWater","maxcombo":"440","count50":"0","count100":"14","count300":"307","countmiss":"0","countkatu":"12","countgeki":"61","perfect":"1","enabled_mods":"72","user_id":"176037","date":"2010-10-14 03:07:15","rank":"SH","pp":"144.241"},{"score_id":"446815896","score":"4111820","username":"Kubu","maxcombo":"439","count50":"0","count100":"17","count300":"304","countmiss":"0","countkatu":"15","countgeki":"58","perfect":"0","enabled_mods":"76","user_id":"29130","date":"2011-09-28 03:08:38","rank":"SH","pp":"135.535"},{"score_id":"1359675133","score":"4110314","username":"oooooa","maxcombo":"439","count50":"0","count100":"18","count300":"303","countmiss":"0","countkatu":"15","countgeki":"58","perfect":"0","enabled_mods":"72","user_id":"1608710","date":"2013-08-17 19:26:01","rank":"SH","pp":"133.074"},{"score_id":"1130066419","score":"4109797","username":"erk","maxcombo":"440","count50":"0","count100":"19","count300":"302","countmiss":"0","countkatu":"13","countgeki":"60","perfect":"1","enabled_mods":"72","user_id":"1107099","date":"2013-04-05 19:59:40","rank":"SH","pp":"130.967"},{"score_id":"974006945","score":"4106566","username":"Zeki-","maxcombo":"440","count50":"0","count100":"17","count300":"304","countmiss":"0","countkatu":"14","countgeki":"59","perfect":"1","enabled_mods":"72","user_id":"889248","date":"2012-12-16 09:17:26","rank":"SH","pp":"135.72"},{"score_id":"1702839803","score":"4104358","username":"IceYoshi","maxcombo":"439","count50":"2","count100":"12","count300":"307","countmiss":"0","countkatu":"7","countgeki":"64","perfect":"0","enabled_mods":"72","user_id":"1021715","date":"2014-02-11 21:07:04","rank":"SH","pp":"142.508"},{"score_id":"1195415401","score":"4104328","username":"Ilayu","maxcombo":"440","count50":"1","count100":"15","count300":"305","countmiss":"0","countkatu":"12","countgeki":"60","perfect":"1","enabled_mods":"72","user_id":"898851","date":"2013-05-18 21:15:18","rank":"SH","pp":"137.684"},{"score_id":"1187639990","score":"4103844","username":"Avner","maxcombo":"440","count50":"2","count100":"17","count300":"302","countmiss":"0","countkatu":"12","countgeki":"59","perfect":"1","enabled_mods":"72","user_id":"1701569","date":"2013-05-13 21:02:58","rank":"SH","pp":"129.881"},{"score_id":"1898930123","score":"4099735","username":"crippletoytl","maxcombo":"440","count50":"2","count100":"17","count300":"302","countmiss":"0","countkatu":"12","countgeki":"60","perfect":"1","enabled_mods":"72","user_id":"3256645","date":"2015-03-09 04:53:00","rank":"SH","pp":"129.881"},{"score_id":"680593475","score":"4096745","username":"DaIc","maxcombo":"440","count50":"0","count100":"14","count300":"307","countmiss":"0","countkatu":"10","countgeki":"63","perfect":"1","enabled_mods":"72","user_id":"675841","date":"2012-04-28 20:56:13","rank":"SH","pp":"144.241"},{"score_id":"1163009579","score":"4094581","username":"SapphireGhost","maxcombo":"440","count50":"0","count100":"14","count300":"307","countmiss":"0","countkatu":"10","countgeki":"63","perfect":"1","enabled_mods":"584","user_id":"388602","date":"2013-04-28 11:38:51","rank":"SH","pp":"144.241"},{"score_id":"1717402285","score":"4089594","username":"Airis","maxcombo":"440","count50":"1","count100":"16","count300":"304","countmiss":"0","countkatu":"11","countgeki":"61","perfect":"1","enabled_mods":"584","user_id":"1471889","date":"2014-03-18 02:18:19","rank":"SH","pp":"135.088"},{"score_id":"1950607429","score":"4087237","username":"Wilchq","maxcombo":"438","count50":"0","count100":"14","count300":"307","countmiss":"0","countkatu":"9","countgeki":"64","perfect":"0","enabled_mods":"72","user_id":"2021758","date":"2015-06-30 23:05:22","rank":"SH","pp":"143.872"},{"score_id":"584631460","score":"4087069","username":"Galmang","maxcombo":"440","count50":"2","count100":"15","count300":"304","countmiss":"0","countkatu":"10","countgeki":"61","perfect":"1","enabled_mods":"76","user_id":"439392","date":"2012-02-07 16:17:54","rank":"SH","pp":"134.468"},{"score_id":"1822272855","score":"4084214","username":"EmingK","maxcombo":"440","count50":"0","count100":"17","count300":"304","countmiss":"0","countkatu":"10","countgeki":"63","perfect":"1","enabled_mods":"584","user_id":"2021118","date":"2014-11-23 18:26:04","rank":"SH","pp":"135.72"},{"score_id":"1836409156","score":"4082294","username":"WilczekCK","maxcombo":"440","count50":"1","count100":"19","count300":"301","countmiss":"0","countkatu":"12","countgeki":"60","perfect":"1","enabled_mods":"72","user_id":"2427116","date":"2014-12-24 20:07:59","rank":"SH","pp":"128.322"},{"score_id":"1747690399","score":"4072022","username":"osu2667","maxcombo":"439","count50":"2","count100":"16","count300":"303","countmiss":"0","countkatu":"9","countgeki":"63","perfect":"0","enabled_mods":"72","user_id":"720867","date":"2014-05-30 00:06:13","rank":"SH","pp":"131.908"},{"score_id":"1905860280","score":"4068555","username":"Dashie5","maxcombo":"439","count50":"0","count100":"18","count300":"303","countmiss":"0","countkatu":"11","countgeki":"62","perfect":"0","enabled_mods":"72","user_id":"1861241","date":"2015-03-24 00:52:20","rank":"SH","pp":"133.074"},{"score_id":"1181228740","score":"4062184","username":"Dtotly","maxcombo":"440","count50":"1","count100":"25","count300":"295","countmiss":"0","countkatu":"15","countgeki":"57","perfect":"1","enabled_mods":"72","user_id":"1061625","date":"2013-05-09 23:41:44","rank":"SH","pp":"118.437"},{"score_id":"1692928411","score":"4059948","username":"BloodM0nk","maxcombo":"440","count50":"2","count100":"18","count300":"301","countmiss":"0","countkatu":"13","countgeki":"58","perfect":"1","enabled_mods":"72","user_id":"2174403","date":"2014-01-27 05:27:05","rank":"SH","pp":"127.82"},{"score_id":"1772162530","score":"4054582","username":"Adamqs","maxcombo":"440","count50":"3","count100":"16","count300":"302","countmiss":"0","countkatu":"11","countgeki":"60","perfect":"1","enabled_mods":"72","user_id":"613592","date":"2014-07-24 21:32:15","rank":"SH","pp":"129.352"},{"score_id":"399330521","score":"4051710","username":"CSY the corrupt","maxcombo":"440","count50":"0","count100":"19","count300":"302","countmiss":"0","countkatu":"14","countgeki":"59","perfect":"1","enabled_mods":"72","user_id":"304513","date":"2011-08-10 22:24:22","rank":"SH","pp":"130.967"},{"score_id":"702319736","score":"4045896","username":"aod","maxcombo":"440","count50":"4","count100":"14","count300":"303","countmiss":"0","countkatu":"9","countgeki":"63","perfect":"1","enabled_mods":"72","user_id":"723100","date":"2012-05-16 19:30:45","rank":"A","pp":"130.967"},{"score_id":"1849055427","score":"4043791","username":"sumaru100","maxcombo":"440","count50":"0","count100":"21","count300":"300","countmiss":"0","countkatu":"14","countgeki":"59","perfect":"1","enabled_mods":"72","user_id":"1872256","date":"2015-01-09 03:09:14","rank":"SH","pp":"126.844"},{"score_id":"1148184257","score":"4043028","username":"N a s y a","maxcombo":"440","count50":"0","count100":"25","count300":"296","countmiss":"0","countkatu":"17","countgeki":"56","perfect":"1","enabled_mods":"72","user_id":"1473106","date":"2013-04-18 17:30:33","rank":"SH","pp":"120.165"},{"score_id":"935689688","score":"4028001","username":"Dariuski","maxcombo":"439","count50":"1","count100":"23","count300":"297","countmiss":"0","countkatu":"14","countgeki":"58","perfect":"0","enabled_mods":"76","user_id":"1324115","date":"2012-11-17 10:38:50","rank":"SH","pp":"121.091"},{"score_id":"1915163090","score":"4024572","username":"LosingCrayon","maxcombo":"440","count50":"0","count100":"0","count300":"321","countmiss":"0","countkatu":"0","countgeki":"73","perfect":"1","enabled_mods":"576","user_id":"4710974","date":"2015-04-12 02:58:09","rank":"X","pp":"209.544"},{"score_id":"1810351220","score":"4023750","username":"-Ryo","maxcombo":"439","count50":"2","count100":"23","count300":"296","countmiss":"0","countkatu":"15","countgeki":"56","perfect":"0","enabled_mods":"72","user_id":"3113141","date":"2014-10-26 10:31:03","rank":"SH","pp":"119.27"},{"score_id":"1765673381","score":"4012740","username":"dv_vb","maxcombo":"440","count50":"1","count100":"27","count300":"293","countmiss":"0","countkatu":"18","countgeki":"54","perfect":"1","enabled_mods":"72","user_id":"4187349","date":"2014-07-09 19:38:53","rank":"SH","pp":"115.972"},{"score_id":"1372696996","score":"4010424","username":"NeedBackup","maxcombo":"440","count50":"0","count100":"2","count300":"319","countmiss":"0","countkatu":"2","countgeki":"71","perfect":"1","enabled_mods":"1024","user_id":"1162534","date":"2013-08-24 12:34:53","rank":"SH","pp":"89.8985"},{"score_id":"602560294","score":"4009610","username":"ZeffiR","maxcombo":"440","count50":"0","count100":"2","count300":"319","countmiss":"0","countkatu":"2","countgeki":"71","perfect":"1","enabled_mods":"64","user_id":"894697","date":"2012-02-23 08:37:33","rank":"S","pp":"194.268"},{"score_id":"1236447149","score":"4003805","username":"Stickie","maxcombo":"440","count50":"0","count100":"23","count300":"298","countmiss":"0","countkatu":"16","countgeki":"57","perfect":"1","enabled_mods":"72","user_id":"1248732","date":"2013-06-12 10:27:23","rank":"SH","pp":"123.267"},{"score_id":"1909093893","score":"4003259","username":"shinkw12","maxcombo":"440","count50":"1","count100":"22","count300":"298","countmiss":"0","countkatu":"17","countgeki":"55","perfect":"1","enabled_mods":"104","user_id":"543176","date":"2015-03-30 21:06:49","rank":"SH","pp":"122.855"},{"score_id":"1475332061","score":"3996540","username":"Aisu Kurimu","maxcombo":"440","count50":"0","count100":"3","count300":"318","countmiss":"0","countkatu":"3","countgeki":"70","perfect":"1","enabled_mods":"64","user_id":"1471011","date":"2013-10-19 23:51:52","rank":"S","pp":"187.375"},{"score_id":"1808050563","score":"3995831","username":"Hello-","maxcombo":"440","count50":"0","count100":"28","count300":"293","countmiss":"0","countkatu":"17","countgeki":"56","perfect":"1","enabled_mods":"584","user_id":"2565819","date":"2014-10-20 15:29:28","rank":"SH","pp":"116.261"},{"score_id":"800410610","score":"3994880","username":"Icsia","maxcombo":"440","count50":"1","count100":"31","count300":"289","countmiss":"0","countkatu":"19","countgeki":"53","perfect":"1","enabled_mods":"72","user_id":"548250","date":"2012-07-28 14:10:02","rank":"SH","pp":"111.966"},{"score_id":"1493317918","score":"3992534","username":"hameron120","maxcombo":"440","count50":"0","count100":"4","count300":"317","countmiss":"0","countkatu":"4","countgeki":"69","perfect":"1","enabled_mods":"64","user_id":"3375977","date":"2013-10-28 22:13:25","rank":"S","pp":"180.938"},{"score_id":"629796354","score":"3985736","username":"CrownSando","maxcombo":"439","count50":"1","count100":"26","count300":"294","countmiss":"0","countkatu":"14","countgeki":"58","perfect":"0","enabled_mods":"76","user_id":"524554","date":"2012-03-17 16:02:27","rank":"SH","pp":"116.976"}]
```
mapid: 57435 
mode: 0
username: Lorella
userID: 3436303
rank as of time of writing: 6
https://osu.ppy.sh/api/get_scores?k=<key>&b=57435
```
[{"score_id":"1735326068","score":"4272595","username":"B e N i","maxcombo":"458","count50":"0","count100":"19","count300":"279","countmiss":"0","countkatu":"15","countgeki":"76","perfect":"1","enabled_mods":"88","user_id":"733878","date":"2014-04-30 20:57:17","rank":"SH","pp":"93.5555"},{"score_id":"1710612926","score":"4174236","username":"No01","maxcombo":"458","count50":"0","count100":"30","count300":"268","countmiss":"0","countkatu":"19","countgeki":"72","perfect":"1","enabled_mods":"88","user_id":"2259709","date":"2014-03-01 23:18:57","rank":"A","pp":"74.8826"},{"score_id":"1716910375","score":"4158680","username":"meT1X","maxcombo":"458","count50":"0","count100":"32","count300":"266","countmiss":"0","countkatu":"20","countgeki":"71","perfect":"1","enabled_mods":"88","user_id":"790453","date":"2014-03-16 21:28:29","rank":"A","pp":"72.874"},{"score_id":"1017636894","score":"4144908","username":"Neab","maxcombo":"458","count50":"0","count100":"7","count300":"291","countmiss":"0","countkatu":"4","countgeki":"87","perfect":"1","enabled_mods":"72","user_id":"916693","date":"2013-01-17 02:04:17","rank":"SH","pp":"89.2218"},{"score_id":"832666399","score":"4141885","username":"Gundam-Dude","maxcombo":"458","count50":"0","count100":"6","count300":"292","countmiss":"0","countkatu":"3","countgeki":"88","perfect":"1","enabled_mods":"108","user_id":"130748","date":"2012-08-20 12:03:33","rank":"SH","pp":"92.3093"},{"score_id":"1538272095","score":"4114389","username":"Lorella","maxcombo":"455","count50":"0","count100":"28","count300":"269","countmiss":"1","countkatu":"22","countgeki":"68","perfect":"0","enabled_mods":"88","user_id":"3436303","date":"2013-11-20 01:27:14","rank":"A","pp":"73.2582"},{"score_id":"957581167","score":"4067745","username":"Dsan","maxcombo":"458","count50":"0","count100":"16","count300":"282","countmiss":"0","countkatu":"12","countgeki":"79","perfect":"1","enabled_mods":"72","user_id":"1266166","date":"2012-12-04 11:38:13","rank":"SH","pp":"69.6178"},{"score_id":"1728583032","score":"4046990","username":"randomizer89","maxcombo":"458","count50":"3","count100":"34","count300":"261","countmiss":"0","countkatu":"16","countgeki":"72","perfect":"1","enabled_mods":"88","user_id":"648613","date":"2014-04-14 14:02:12","rank":"A","pp":"68.541"},{"score_id":"1289482085","score":"4044177","username":"Crystal-","maxcombo":"458","count50":"0","count100":"19","count300":"279","countmiss":"0","countkatu":"15","countgeki":"76","perfect":"1","enabled_mods":"72","user_id":"2006663","date":"2013-07-11 14:35:54","rank":"SH","pp":"65.4992"},{"score_id":"126360276","score":"4027477","username":"light12389","maxcombo":"458","count50":"0","count100":"16","count300":"282","countmiss":"0","countkatu":"12","countgeki":"79","perfect":"1","enabled_mods":"1032","user_id":"143777","date":"2010-07-26 00:52:40","rank":"SH","pp":"29.2742"},{"score_id":"1007113309","score":"4001321","username":"kiyorin","maxcombo":"458","count50":"0","count100":"17","count300":"281","countmiss":"0","countkatu":"15","countgeki":"76","perfect":"1","enabled_mods":"72","user_id":"1449702","date":"2013-01-09 02:58:09","rank":"SH","pp":"68.1412"},{"score_id":"1945907589","score":"3995684","username":"WubWoofWolf","maxcombo":"458","count50":"0","count100":"0","count300":"298","countmiss":"0","countkatu":"0","countgeki":"91","perfect":"1","enabled_mods":"64","user_id":"39828","date":"2015-06-20 18:50:44","rank":"X","pp":"111.225"},{"score_id":"1386118270","score":"3988957","username":"Silynn","maxcombo":"458","count50":"0","count100":"46","count300":"252","countmiss":"0","countkatu":"30","countgeki":"61","perfect":"1","enabled_mods":"600","user_id":"1171628","date":"2013-08-31 08:42:35","rank":"A","pp":"64.8065"},{"score_id":"1413633728","score":"3981695","username":"fripSide","maxcombo":"458","count50":"0","count100":"2","count300":"296","countmiss":"0","countkatu":"2","countgeki":"89","perfect":"1","enabled_mods":"1024","user_id":"2488457","date":"2013-09-15 13:48:46","rank":"SH","pp":"40.235"},{"score_id":"610659189","score":"3979293","username":"cr1m","maxcombo":"458","count50":"0","count100":"20","count300":"278","countmiss":"0","countkatu":"12","countgeki":"79","perfect":"1","enabled_mods":"72","user_id":"803766","date":"2012-03-01 01:46:44","rank":"SH","pp":"64.3193"},{"score_id":"693090196","score":"3974563","username":"Colored","maxcombo":"458","count50":"2","count100":"38","count300":"258","countmiss":"0","countkatu":"28","countgeki":"61","perfect":"1","enabled_mods":"88","user_id":"827563","date":"2012-05-09 00:12:38","rank":"A","pp":"67.0422"},{"score_id":"1481385556","score":"3967716","username":"- cookie -","maxcombo":"456","count50":"1","count100":"49","count300":"247","countmiss":"1","countkatu":"28","countgeki":"61","perfect":"0","enabled_mods":"88","user_id":"349523","date":"2013-10-23 00:25:47","rank":"B","pp":"61.1642"},{"score_id":"1828479269","score":"3965877","username":"Dailycare","maxcombo":"458","count50":"0","count100":"20","count300":"278","countmiss":"0","countkatu":"14","countgeki":"77","perfect":"1","enabled_mods":"72","user_id":"1634445","date":"2014-12-07 19:25:54","rank":"SH","pp":"64.3193"},{"score_id":"1554588898","score":"3953975","username":"Nanoiir","maxcombo":"458","count50":"0","count100":"23","count300":"275","countmiss":"0","countkatu":"16","countgeki":"75","perfect":"1","enabled_mods":"72","user_id":"1326391","date":"2013-11-27 15:30:55","rank":"SH","pp":"61.2666"},{"score_id":"668930459","score":"3949944","username":"funshine","maxcombo":"458","count50":"1","count100":"46","count300":"251","countmiss":"0","countkatu":"34","countgeki":"56","perfect":"1","enabled_mods":"88","user_id":"772111","date":"2012-04-19 01:58:34","rank":"A","pp":"64.4072"},{"score_id":"1021409219","score":"3947679","username":"RedVermilion","maxcombo":"458","count50":"0","count100":"5","count300":"293","countmiss":"0","countkatu":"5","countgeki":"86","perfect":"1","enabled_mods":"576","user_id":"859050","date":"2013-01-19 22:18:14","rank":"S","pp":"90.8925"},{"score_id":"1145468159","score":"3929182","username":"I s i s","maxcombo":"458","count50":"0","count100":"27","count300":"271","countmiss":"0","countkatu":"19","countgeki":"72","perfect":"1","enabled_mods":"72","user_id":"244226","date":"2013-04-16 13:26:08","rank":"SH","pp":"58.1291"},{"score_id":"1858460741","score":"3928066","username":"kuppatruppa","maxcombo":"458","count50":"0","count100":"23","count300":"275","countmiss":"0","countkatu":"17","countgeki":"74","perfect":"1","enabled_mods":"72","user_id":"2879260","date":"2015-01-18 10:18:25","rank":"SH","pp":"61.2666"},{"score_id":"690044733","score":"3926422","username":"Uan","maxcombo":"458","count50":"0","count100":"7","count300":"291","countmiss":"0","countkatu":"7","countgeki":"84","perfect":"1","enabled_mods":"64","user_id":"147623","date":"2012-05-06 11:36:10","rank":"S","pp":"84.5977"},{"score_id":"1698653308","score":"3906360","username":"-Ryo","maxcombo":"458","count50":"0","count100":"27","count300":"271","countmiss":"0","countkatu":"17","countgeki":"74","perfect":"1","enabled_mods":"72","user_id":"3113141","date":"2014-02-01 11:59:34","rank":"SH","pp":"58.1291"},{"score_id":"1842680105","score":"3903170","username":"hoozimajiget","maxcombo":"458","count50":"0","count100":"13","count300":"285","countmiss":"0","countkatu":"10","countgeki":"81","perfect":"1","enabled_mods":"64","user_id":"215567","date":"2015-01-02 12:36:04","rank":"S","pp":"70.3977"},{"score_id":"1712346718","score":"3903120","username":"Sochi","maxcombo":"457","count50":"1","count100":"23","count300":"274","countmiss":"0","countkatu":"15","countgeki":"75","perfect":"0","enabled_mods":"72","user_id":"3754964","date":"2014-03-06 02:08:34","rank":"SH","pp":"60.0959"},{"score_id":"595558739","score":"3894762","username":"GGBY","maxcombo":"458","count50":"0","count100":"9","count300":"289","countmiss":"0","countkatu":"8","countgeki":"83","perfect":"1","enabled_mods":"64","user_id":"629717","date":"2012-02-17 13:52:40","rank":"S","pp":"79.1552"},{"score_id":"1454173393","score":"3883457","username":"instantlovee","maxcombo":"458","count50":"0","count100":"28","count300":"270","countmiss":"0","countkatu":"17","countgeki":"74","perfect":"1","enabled_mods":"72","user_id":"2533128","date":"2013-10-08 05:30:42","rank":"SH","pp":"57.4803"},{"score_id":"671121522","score":"3881605","username":"adi77715","maxcombo":"457","count50":"1","count100":"14","count300":"283","countmiss":"0","countkatu":"11","countgeki":"79","perfect":"0","enabled_mods":"64","user_id":"712380","date":"2012-04-21 00:29:30","rank":"S","pp":"66.4181"},{"score_id":"1039583326","score":"3874530","username":"Xions","maxcombo":"458","count50":"0","count100":"11","count300":"287","countmiss":"0","countkatu":"9","countgeki":"82","perfect":"1","enabled_mods":"64","user_id":"751970","date":"2013-02-01 17:12:11","rank":"S","pp":"74.4543"},{"score_id":"1807764034","score":"3872987","username":"ONew","maxcombo":"458","count50":"0","count100":"10","count300":"288","countmiss":"0","countkatu":"8","countgeki":"83","perfect":"1","enabled_mods":"64","user_id":"1294979","date":"2014-10-19 21:18:01","rank":"S","pp":"76.7184"},{"score_id":"967348599","score":"3870304","username":"german47","maxcombo":"458","count50":"0","count100":"11","count300":"287","countmiss":"0","countkatu":"9","countgeki":"82","perfect":"1","enabled_mods":"64","user_id":"795087","date":"2012-12-11 16:54:02","rank":"S","pp":"74.4543"},{"score_id":"1391912029","score":"3867467","username":"voooooy","maxcombo":"458","count50":"2","count100":"21","count300":"275","countmiss":"0","countkatu":"12","countgeki":"77","perfect":"1","enabled_mods":"72","user_id":"1909540","date":"2013-09-03 08:10:56","rank":"SH","pp":"60.8213"},{"score_id":"125432646","score":"3858614","username":"loveFantasy","maxcombo":"458","count50":"0","count100":"16","count300":"282","countmiss":"0","countkatu":"14","countgeki":"77","perfect":"1","enabled_mods":"64","user_id":"27489","date":"2010-07-24 05:44:15","rank":"S","pp":"65.3373"},{"score_id":"1034067339","score":"3857309","username":"TaNaBaTa","maxcombo":"458","count50":"0","count100":"14","count300":"284","countmiss":"0","countkatu":"12","countgeki":"79","perfect":"1","enabled_mods":"64","user_id":"756273","date":"2013-01-28 19:42:14","rank":"S","pp":"68.584"},{"score_id":"707061957","score":"3832317","username":"miya3con","maxcombo":"456","count50":"0","count100":"29","count300":"268","countmiss":"1","countkatu":"20","countgeki":"70","perfect":"0","enabled_mods":"76","user_id":"633845","date":"2012-05-20 09:27:58","rank":"B","pp":"54.3774"},{"score_id":"126402080","score":"3830386","username":"Vpalach","maxcombo":"458","count50":"0","count100":"16","count300":"282","countmiss":"0","countkatu":"14","countgeki":"77","perfect":"1","enabled_mods":"68","user_id":"232729","date":"2010-07-26 03:05:01","rank":"S","pp":"65.3373"},{"score_id":"1275745577","score":"3822415","username":"Chema","maxcombo":"458","count50":"3","count100":"28","count300":"267","countmiss":"0","countkatu":"17","countgeki":"72","perfect":"1","enabled_mods":"72","user_id":"1075008","date":"2013-07-03 22:23:42","rank":"A","pp":"55.4325"},{"score_id":"977021579","score":"3821466","username":"My Accuracy Sucks","maxcombo":"458","count50":"0","count100":"16","count300":"282","countmiss":"0","countkatu":"11","countgeki":"80","perfect":"1","enabled_mods":"68","user_id":"1693771","date":"2012-12-18 12:18:44","rank":"S","pp":"65.3373"},{"score_id":"236469773","score":"3815217","username":"nVidi4x","maxcombo":"458","count50":"0","count100":"18","count300":"280","countmiss":"0","countkatu":"17","countgeki":"74","perfect":"1","enabled_mods":"64","user_id":"203181","date":"2011-02-13 05:06:23","rank":"S","pp":"62.541"},{"score_id":"1784343378","score":"3813665","username":"[-Kushii-]","maxcombo":"458","count50":"0","count100":"20","count300":"278","countmiss":"0","countkatu":"11","countgeki":"80","perfect":"1","enabled_mods":"64","user_id":"2361122","date":"2014-08-21 16:03:06","rank":"S","pp":"60.1337"},{"score_id":"1939946568","score":"3813508","username":"Nyirti","maxcombo":"458","count50":"1","count100":"16","count300":"281","countmiss":"0","countkatu":"13","countgeki":"77","perfect":"1","enabled_mods":"64","user_id":"1111025","date":"2015-06-07 05:19:47","rank":"S","pp":"63.5409"},{"score_id":"1642188178","score":"3812644","username":"kanade takahashi","maxcombo":"458","count50":"0","count100":"19","count300":"279","countmiss":"0","countkatu":"15","countgeki":"76","perfect":"1","enabled_mods":"576","user_id":"1624368","date":"2014-01-04 22:01:51","rank":"S","pp":"61.2922"},{"score_id":"880547329","score":"3811845","username":"TokisakiKurumi","maxcombo":"458","count50":"0","count100":"16","count300":"282","countmiss":"0","countkatu":"14","countgeki":"77","perfect":"1","enabled_mods":"64","user_id":"1291134","date":"2012-09-30 16:20:54","rank":"S","pp":"65.3373"},{"score_id":"1066201462","score":"3808082","username":"AroMe","maxcombo":"458","count50":"0","count100":"24","count300":"274","countmiss":"0","countkatu":"20","countgeki":"71","perfect":"1","enabled_mods":"64","user_id":"536207","date":"2013-02-19 15:48:40","rank":"S","pp":"56.2795"},{"score_id":"1700144020","score":"3806905","username":"Lucaito","maxcombo":"458","count50":"1","count100":"22","count300":"275","countmiss":"0","countkatu":"12","countgeki":"78","perfect":"1","enabled_mods":"64","user_id":"1475419","date":"2014-02-05 03:14:44","rank":"S","pp":"56.9168"},{"score_id":"691835846","score":"3803677","username":"Arirukuchika","maxcombo":"452","count50":"0","count100":"10","count300":"287","countmiss":"1","countkatu":"8","countgeki":"82","perfect":"0","enabled_mods":"64","user_id":"1091729","date":"2012-05-07 21:58:05","rank":"A","pp":"71.5452"},{"score_id":"1566188025","score":"3803059","username":"ReLentles","maxcombo":"458","count50":"0","count100":"18","count300":"280","countmiss":"0","countkatu":"14","countgeki":"77","perfect":"1","enabled_mods":"64","user_id":"721757","date":"2013-12-02 20:42:26","rank":"S","pp":"62.541"},{"score_id":"375632779","score":"3800209","username":"Camyu","maxcombo":"458","count50":"0","count100":"16","count300":"282","countmiss":"0","countkatu":"11","countgeki":"80","perfect":"1","enabled_mods":"64","user_id":"521087","date":"2011-07-18 16:57:34","rank":"S","pp":"65.3373"}]
```

There are more users like these 2

**Comment by peppy** [comment]
Should be fixed now.

**Comment by Piotrekol** [comment]
Second user (Lorella) seems to still exist on api/score page.

**Comment by peppy** [comment]
Oops, didn't push to enough servers. Try now!

**Comment by Piotrekol** [comment]
It looks like it is fixed on api, but still shown on standard score pages.
I'll close this issue after we do next full processing of osu!api(today/tomorrow)
